app:
  port: 8080
  name: "Fiber App"
  env: "development"

db:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  name: "postgres"
  ssl: "disable"

jwt:
  secret: "your-256-bit-secret-key-here"
  access_expiry_minutes: 60
  refresh_expiry_days: 7
